/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guia2;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jnadi
 */
public class planilla extends javax.swing.JFrame {
    
    DefaultTableModel modelo = new DefaultTableModel();
    String [] columnas = {"DPI", "NOMBRE", "APELLIDO", "SALARIO", "CATEGORIA", "PUESTO", "TOTAL"};
    double salario, CatA = 500, CatB = 350, CatC = 150, total;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(planilla.class.getName());

    /**
    
     */
    public planilla() {
        initComponents();
        this.setTitle("Planilla Chamba"); 
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        modelo.setColumnIdentifiers(columnas);
        tablita.setModel(modelo);
       jcbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE CATEGORIA", "A", "B", "C", "D" }));
        jcbxPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE PUESTO", "JEFE", "SECRETARIO", "TRABAJADOR", "LIMPIEZA" }));
        
        
        modelo.setColumnIdentifiers(columnas);
        tablita.setModel(modelo); 
    
    modelo.setColumnIdentifiers(columnas);
    tablita.setModel(modelo); 
    }
    
    public void totalSalario() {
   
   salario = Double.parseDouble(jtxtSalario.getText());
        
       
        String opcionCat = jcbxCategoria.getSelectedItem().toString();
        
        if(opcionCat.equals("A")) {
            total = salario + CatA;
        } else if(opcionCat.equals("B")) {
            total = salario + CatB;
        } else if(opcionCat.equals("C")) {
            total = salario + CatC;
        } else if(opcionCat.equals("D") || opcionCat.equals("SELECCIONE CATEGORIA")) {
            
            total = salario;
        } else {
            total = salario;
        }
    }
    
    public void limpiarCajas() {
    jtxtDpi.setText("");
    jtxtNombre.setText("");
    jtxtApellido.setText("");
    jtxtSalario.setText("");
    jcbxCategoria.setSelectedItem("SELECCIONE CATEGORIA");
    jcbxPuesto.setSelectedItem("SELECCIONE PUESTO");
    jtxtDpi.requestFocus(); // mostrar el cursor
}
    
    //Metodo del boton eliminar
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpi = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        apellidos = new javax.swing.JLabel();
        sal = new javax.swing.JLabel();
        categoria = new javax.swing.JLabel();
        puesto = new javax.swing.JLabel();
        jtxtDpi = new javax.swing.JTextField();
        jtxtNombre = new javax.swing.JTextField();
        jtxtApellido = new javax.swing.JTextField();
        jtxtSalario = new javax.swing.JTextField();
        planilla = new javax.swing.JLabel();
        jcbxCategoria = new javax.swing.JComboBox<>();
        jcbxPuesto = new javax.swing.JComboBox<>();
        insert = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablita = new javax.swing.JTable();
        jbtnEliminar = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dpi.setFont(new java.awt.Font("balatro", 0, 18)); // NOI18N
        dpi.setText("DPI");

        nombre.setFont(new java.awt.Font("balatro", 0, 18)); // NOI18N
        nombre.setText("NOMBRE");

        apellidos.setFont(new java.awt.Font("balatro", 0, 18)); // NOI18N
        apellidos.setText("APELLIDOS");

        sal.setFont(new java.awt.Font("balatro", 0, 18)); // NOI18N
        sal.setText("SALARIO");

        categoria.setFont(new java.awt.Font("balatro", 0, 18)); // NOI18N
        categoria.setText("CATEGORIA");

        puesto.setFont(new java.awt.Font("balatro", 0, 18)); // NOI18N
        puesto.setText("PUESTO");

        jtxtDpi.setFont(new java.awt.Font("balatro", 0, 18)); // NOI18N

        jtxtNombre.setFont(new java.awt.Font("balatro", 0, 18)); // NOI18N

        jtxtApellido.setFont(new java.awt.Font("balatro", 0, 18)); // NOI18N

        jtxtSalario.setFont(new java.awt.Font("balatro", 0, 18)); // NOI18N

        planilla.setFont(new java.awt.Font("balatro", 0, 18)); // NOI18N
        planilla.setText("PLANILLA");

        jcbxCategoria.setFont(new java.awt.Font("balatro", 0, 18)); // NOI18N
        jcbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbxCategoria.addActionListener(this::jcbxCategoriaActionPerformed);

        jcbxPuesto.setFont(new java.awt.Font("balatro", 0, 18)); // NOI18N
        jcbxPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        insert.setFont(new java.awt.Font("balatro", 0, 18)); // NOI18N
        insert.setText("INSERTAR");
        insert.addActionListener(this::insertActionPerformed);

        tablita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablitaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablita);

        jbtnEliminar.setText("ELIMINAR");
        jbtnEliminar.addActionListener(this::jbtnEliminarActionPerformed);

        jbtnEditar.setText("Editar");
        jbtnEditar.addActionListener(this::jbtnEditarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sal)
                            .addComponent(puesto)
                            .addComponent(categoria)
                            .addComponent(dpi)
                            .addComponent(apellidos)
                            .addComponent(nombre))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(planilla)
                                .addComponent(jtxtDpi, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtxtSalario)
                                .addComponent(jcbxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcbxPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(insert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(planilla)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtxtDpi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dpi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombre)
                                .addGap(6, 6, 6))
                            .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellidos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtxtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jcbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(categoria))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbxPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(puesto, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(insert)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbxCategoriaActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        // TODO add your handling code here:
      
    totalSalario();
    
   
    modelo.addRow(new Object[]{
        jtxtDpi.getText(),
        jtxtNombre.getText(),
        jtxtApellido.getText(),
        jtxtSalario.getText(),
        jcbxCategoria.getSelectedItem(),
        jcbxPuesto.getSelectedItem(),
        total
    });
    
   
    limpiarCajas();


    }//GEN-LAST:event_insertActionPerformed

    private void tablitaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablitaMousePressed
        // TODO add your handling code here:
        jtxtDpi.setText(tablita.getValueAt(tablita.getSelectedRow(), 0).toString());
        jtxtNombre.setText(tablita.getValueAt(tablita.getSelectedRow(), 1).toString());
        jtxtApellido.setText(tablita.getValueAt(tablita.getSelectedRow(), 2).toString());
        jtxtSalario.setText(tablita.getValueAt(tablita.getSelectedRow(), 3).toString());
        

        jcbxCategoria.setSelectedItem(tablita.getValueAt(tablita.getSelectedRow(), 4));
        jcbxPuesto.setSelectedItem(tablita.getValueAt(tablita.getSelectedRow(), 5));
    }//GEN-LAST:event_tablitaMousePressed

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
        //Proceder a eliminarlos
        if (modelo.getRowCount() <= 0) {
            JOptionPane.showMessageDialog(null,"No hay registro!!!!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else {
            modelo.removeRow(tablita.getSelectedRow());
            JOptionPane.showMessageDialog(null,"Registro eliminado con éxito!!!!", "Java", JOptionPane.INFORMATION_MESSAGE);
            
            //metodo para limpiar las cajas
            limpiarCajas();
        }
    }//GEN-LAST:event_jbtnEliminarActionPerformed

    private void jbtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditarActionPerformed
        // TODO add your handling code here:
        // Captura los datos que se actualizaran 
        modelo.setValueAt(jtxtDpi.getText(), tablita.getSelectedRow(), 0);
        modelo.setValueAt(jtxtNombre.getText(), tablita.getSelectedRow(), 1);
        modelo.setValueAt(jtxtApellido.getText(), tablita.getSelectedRow(), 2);
        modelo.setValueAt(jtxtSalario.getText(), tablita.getSelectedRow(), 3);
        
        modelo.setValueAt(jcbxCategoria.getSelectedItem(), tablita.getSelectedRow(), 4);
        modelo.setValueAt(jcbxPuesto.getSelectedItem(), tablita.getSelectedRow(), 5);
        
        //Realizar los calculos
        //Metodo Calcular
        totalSalario();
        modelo.setValueAt(total, tablita.getSelectedRow(), 6);
        
        //Limpiar cajas
        limpiarCajas();
    }//GEN-LAST:event_jbtnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new planilla().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidos;
    private javax.swing.JLabel categoria;
    private javax.swing.JLabel dpi;
    private javax.swing.JButton insert;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JComboBox<String> jcbxCategoria;
    private javax.swing.JComboBox<String> jcbxPuesto;
    private javax.swing.JTextField jtxtApellido;
    private javax.swing.JTextField jtxtDpi;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtSalario;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel planilla;
    private javax.swing.JLabel puesto;
    private javax.swing.JLabel sal;
    private javax.swing.JTable tablita;
    // End of variables declaration//GEN-END:variables
}
